version: "3"

services:
  db:
    image: mysql:5.7
    container_name: studenti
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studenti
      MYSQL_USER: studenti
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    network_mode: bridge